# Site settings
title: Riadh fezzani
email: 
description: "Riadh Fezzani curriculum vitae. Doctor in applied mathematics."
baseurl: ""
url: "https://rfezzani.github.io"
twitter_username: 
github_username:  rfezzani

# Build settings
markdown: kramdown
permalink: pretty
