# Site settings
title: Riadh fezzani
email: rfezzani@gmail.com
description: Riadh Fezzani, Doctor in applied mathematics.
baseurl: ""
url: https://rfezzani.github.io
github_username:  rfezzani

# Build settings
markdown: kramdown
permalink: pretty
